name: Release Geode Mod

on:
  workflow_dispatch:

jobs:
  release:
    name: Release mod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: hiimjasmine00/BareBonesMod
          path: BareBonesMod

      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: BareBonesMod
          replace: true
          prerelease: true
